export type ShowcaseCategory =
  | "all"
  | "zero-knowledge"
  | "analytics"
  | "viewer"
  | "gates"
  | "alerts"
  | "admin"
  | "email";

export interface ShowcaseItem {
  id: string;
  filename: string;
  category: "zero-knowledge" | "analytics" | "viewer" | "gates" | "alerts" | "admin" | "email";
  titleEn: string;
  titleHi: string;
  badge: string;
  badgeColor?: "emerald" | "blue" | "amber" | "rose" | "purple";
  descriptionEn: string;
  descriptionHi: string;
  tags: string[];
  proofPoints: string[];
  highlight?: boolean;
}

export const SHOWCASE_CATEGORIES: { id: ShowcaseCategory; labelEn: string; labelHi: string }[] = [
  { id: "all", labelEn: "All Verified Captures", labelHi: "सभी सत्यापित स्क्रीनशॉट" },
  { id: "zero-knowledge", labelEn: "Zero-Knowledge & Vault", labelHi: "ज़ीरो-नॉलेज और वॉल्ट" },
  { id: "analytics", labelEn: "DuckDB & Telemetry", labelHi: "डकडीबी और टेलीमेट्री" },
  { id: "viewer", labelEn: "Secure Viewer & Q&A", labelHi: "सुरक्षित व्यूअर और प्रश्नोत्तरी" },
  { id: "gates", labelEn: "Encryption & Link Studio", labelHi: "एन्क्रिप्शन और लिंक स्टूडियो" },
  { id: "alerts", labelEn: "Stoat Webhook Alerts", labelHi: "स्टोट वेबहुक अलर्ट" },
  { id: "admin", labelEn: "Infra, Health & Audit", labelHi: "इन्फ्रा, हेल्थ और ऑडिट" },
  { id: "email", labelEn: "Email Relay (GAS)", labelHi: "ईमेल रिले (GAS)" },
];

export const SHOWCASE_ITEMS: ShowcaseItem[] = [
  // ==========================================
  // 1. ZERO-KNOWLEDGE & CRYPTOGRAPHIC PROOFS
  // ==========================================
  {
    id: "zk-ciphertext-proof",
    filename: "Notepad3_bkYXOeH1CB.png",
    category: "zero-knowledge",
    titleEn: "Zero-Knowledge Ciphertext Proof in Notepad3",
    titleHi: "Notepad3 में शून्य-ज्ञान सिफरटेक्स्ट प्रमाण",
    badge: "Cryptographic Proof",
    badgeColor: "emerald",
    highlight: true,
    descriptionEn: "Raw Backblaze B2 ciphertext blob opened in Notepad3. Proves 100% encrypted random bytes with 0 plaintext strings, zero file headers, and zero leaked metadata on the storage server.",
    descriptionHi: "Notepad3 में खोला गया बैकब्लेज B2 का रॉ सिफरटेक्स्ट ब्लॉक। यह प्रमाणित करता है कि स्टोरेज सर्वर पर 100% एन्क्रिप्टेड बाइट्स हैं, शून्य प्लेनटेक्स्ट स्ट्रिंग्स और शून्य लीक हुआ मेटाडेटा।",
    tags: ["AES-GCM-256", "Backblaze B2", "Zero-Knowledge", "Raw Blob"],
    proofPoints: [
      "Zero unencrypted plaintext bytes in storage",
      "Cryptographic random entropy in payload",
      "Decryption key (#k=...) completely absent from server files",
    ],
  },
  {
    id: "b2-cloud-storage-console",
    filename: "brave_yTfqtB0lpn.png",
    category: "zero-knowledge",
    titleEn: "Backblaze B2 Vault Storage Console",
    titleHi: "बैकब्लेज B2 वॉल्ट स्टोरेज कंसोल",
    badge: "Cloud Storage",
    badgeColor: "blue",
    descriptionEn: "Live Backblaze B2 cloud bucket console showing blind encrypted document storage (blindshare-vault/docs/.../doc_...cipher, 2.6 MB). Server stores only opaque ciphertext chunks.",
    descriptionHi: "लाइव बैकब्लेज B2 क्लाउड बकेट कंसोल जो ब्लाइंड एन्क्रिप्टेड दस्तावेज़ (doc_...cipher, 2.6 MB) प्रदर्शित करता है। सर्वर केवल एन्क्रिप्टेड सिफरटेक्स्ट रखता है।",
    tags: ["Backblaze B2", "S3-Compatible", "₹0 Free Tier", "Opaque Chunks"],
    proofPoints: [
      "Cloudflare Bandwidth Alliance $0 egress",
      "Files saved as opaque .cipher blobs",
      "Total zero access for cloud storage administrators",
    ],
  },
  {
    id: "master-vault-derivation",
    filename: "brave_eEweBvIWAP.png",
    category: "zero-knowledge",
    titleEn: "Owner Master Key Vault Restoration (PBKDF2 100k)",
    titleHi: "मास्टर की वॉल्ट रीस्टोरेशन (PBKDF2 100k राउंड्स)",
    badge: "WebCrypto PBKDF2",
    badgeColor: "amber",
    highlight: true,
    descriptionEn: "Client-side WebCrypto PBKDF2 (100,000 rounds) key derivation executing in the browser in 4,561ms. Unlocks all document keys locally without ever transmitting master passphrase.",
    descriptionHi: "ब्राउज़र में 4,561ms में चलने वाला क्लाइंट-साइड WebCrypto PBKDF2 (100,000 राउंड्स) की-डेरिवेशन। मास्टर पासफ़्रेज़ को सर्वर पर भेजे बिना सभी दस्तावेज़ कुंजियों को स्थानीय रूप से अनलॉक करता है।",
    tags: ["PBKDF2", "100k Rounds", "WebCrypto", "Zero-Knowledge Vault"],
    proofPoints: [
      "4,561ms computational proof-of-work in browser memory",
      "AES-KW-256 wrapped key derivation",
      "Zero plain password transmission over network",
    ],
  },
  {
    id: "master-vault-unlocked",
    filename: "brave_i1nnbgU2e0.png",
    category: "zero-knowledge",
    titleEn: "Decrypted Master Vault Active State",
    titleHi: "डिक्रिप्टेड मास्टर वॉल्ट सक्रिय स्थिति",
    badge: "Vault Unlocked",
    badgeColor: "emerald",
    descriptionEn: "Client-side Master Vault in unlocked state showing synced zero-knowledge document keys ready for instant one-click sharing across devices with session memory isolation.",
    descriptionHi: "अनलॉक स्थिति में क्लाइंट-साइड मास्टर वॉल्ट जो सत्र मेमोरी आइसोलेशन के साथ सभी डिवाइसों पर त्वरित वन-क्लिक शेयरिंग के लिए तैयार डिक्रिप्टेड दस्तावेज़ कुंजियाँ दिखाता है।",
    tags: ["Vault Synchronization", "Session Isolation", "In-Memory Wiping"],
    proofPoints: [
      "Zero-knowledge multi-device synchronization",
      "In-memory key isolation with auto-lock timer",
      "Encrypted sync payloads stored on Neon DB",
    ],
  },
  {
    id: "forensic-steganography-scanner",
    filename: "brave_Tc1PUfLrsy.png",
    category: "zero-knowledge",
    titleEn: "Forensic Steganography Leak Scanner (99% Match)",
    titleHi: "फॉरेंसिक स्टेग्नोग्राफी लीक स्कैनर (99% सटीकता)",
    badge: "Pillar 5 Security",
    badgeColor: "rose",
    highlight: true,
    descriptionEn: "Forensic leak scanner verifying an exfiltrated screenshot with a 99% confidence match. Detects zero-width invisible viewer IDs, CRC leak hashes, and pinpointed share link origin.",
    descriptionHi: "फॉरेंसिक लीक स्कैनर जो 99% सटीकता के साथ लीक हुए स्क्रीनशॉट को सत्यापित करता है। शून्य-चौड़ाई अदृश्य व्यूअर आईडी, CRC लीक हैश और शेयर लिंक मूल का पता लगाता है।",
    tags: ["Steganography", "Leak Tracing", "Zero-Width Spaces", "CRC-32"],
    proofPoints: [
      "99% confidence origin matching on leaked screenshots",
      "Zero-width unicode watermark embedded into canvas",
      "Pinpoints exact viewer email, timestamp, and IP signature",
    ],
  },
  {
    id: "security-vault-settings",
    filename: "brave_EpDcNoQyCA.png",
    category: "zero-knowledge",
    titleEn: "Cryptographic Vault & KDF Security Configuration",
    titleHi: "क्रिप्टोग्राफ़िक वॉल्ट और KDF सुरक्षा सेटिंग्स",
    badge: "KDF Control",
    badgeColor: "purple",
    descriptionEn: "Cryptographic engine configuration panel allowing founders to select KDF algorithms (Argon2id vs PBKDF2 100k), configure RAM buffer zeroize timers, and enforce hardware isolation.",
    descriptionHi: "क्रिप्टोग्राफिक इंजन कॉन्फ़िगरेशन पैनल जो संस्थापकों को KDF एल्गोरिदम (Argon2id बनाम PBKDF2 100k) चुनने, रैम बफर जीरोइज़ टाइमर सेट करने और हार्डवेयर अलगाव लागू करने की अनुमति देता है।",
    tags: ["Argon2id", "RAM Zeroizing", "Hardware Isolation", "Crypto Ratchet"],
    proofPoints: [
      "Toggleable Argon2id memory-hard hashing against GPU clusters",
      "Inactivity buffer clearing with zeroizeBuffer()",
      "Client-side crypto ratchet and burn-after-reading toggles",
    ],
  },

  // ==========================================
  // 2. REAL-TIME FOUNDER ALERTING (STOAT CHAT)
  // ==========================================
  {
    id: "stoat-doc-opened-alert",
    filename: "gMGRTq3zGO.png",
    category: "alerts",
    titleEn: "Real-Time Stoat Alert: Document Opened",
    titleHi: "रीयल-टाइम स्टोट अलर्ट: दस्तावेज़ खोला गया",
    badge: "Stoat Webhook",
    badgeColor: "amber",
    highlight: true,
    descriptionEn: "Live Stoat #form-logs webhook notification dispatched in under 50ms when a viewer accesses a protected pitch deck. Delivers viewer email, device, country, and dwell start telemetry.",
    descriptionHi: "लाइव स्टोट #form-logs वेबहुक अधिसूचना जो व्यूअर द्वारा पिच डेक खोलने पर 50ms से कम समय में भेजी जाती है। व्यूअर ईमेल, डिवाइस, देश और पढ़ने की शुरुआत का विवरण देती है।",
    tags: ["Stoat Chat", "Revolt API", "Instant Webhook", "Zero-Delay Alerting"],
    proofPoints: [
      "Sub-50ms dispatch latency via edge serverless queue",
      "Detailed viewer email, user-agent, and country flags",
      "Fail-safe fallback with circuit breaker protection",
    ],
  },
  {
    id: "stoat-question-asked-alert",
    filename: "qZoGhGMXzD.png",
    category: "alerts",
    titleEn: "Real-Time Stoat Alert: Slide Question Asked",
    titleHi: "रीयल-टाइम स्टोट अलर्ट: स्लाइड पर प्रश्न पूछा गया",
    badge: "Interactive Q&A",
    badgeColor: "blue",
    descriptionEn: "Instant Stoat #form-logs webhook notification alerting the founder that a reader placed an interactive question pin on Slide 1. Enables real-time founder engagement with investors.",
    descriptionHi: "तुरंत स्टोट #form-logs वेबहुक अधिसूचना जो संस्थापक को सचेत करती है कि पाठक ने स्लाइड 1 पर एक इंटरैक्टिव प्रश्न पिन रखा है। निवेशकों के साथ तत्काल संवाद सक्षम करता है।",
    tags: ["Slide Q&A", "Founder Alerting", "Live Engagement", "Pin Telemetry"],
    proofPoints: [
      "Includes slide number, precise coordinates, and question text",
      "Direct deep link to answer in founder dashboard",
      "Privacy-isolated reader session identifier",
    ],
  },
  {
    id: "stoat-webhook-feed",
    filename: "qnVN75d3pi.png",
    category: "alerts",
    titleEn: "Stoat Notification Stream in Action",
    titleHi: "कार्रवाई में स्टोट अधिसूचना स्ट्रीम",
    badge: "Live Telemetry Feed",
    badgeColor: "emerald",
    descriptionEn: "Continuous stream of real-time viewer events arriving in the founder's Stoat chat channel, providing instant situational awareness during fundraising pitch distributions.",
    descriptionHi: "संस्थापक के स्टोट चैट चैनल में आने वाले रीयल-टाइम व्यूअर इवेंट्स की सतत स्ट्रीम, जो फंडरेजिंग पिच वितरण के दौरान तत्काल जागरूकता प्रदान करती है।",
    tags: ["Event Stream", "Fundraising Telemetry", "High-Velocity Dispatch"],
    proofPoints: [
      "Tracks link creation, document opens, slide changes, and exits",
      "Zero third-party SaaS tracking costs ($0/month)",
      "Revolt bot integration with rich Markdown embeds",
    ],
  },

  // ==========================================
  // 3. TRANSACTIONAL EMAIL RELAY (GOOGLE APPS SCRIPT)
  // ==========================================
  {
    id: "gas-email-diagnostic-verified",
    filename: "brave_hetLrAlKER.png",
    category: "email",
    titleEn: "Google Apps Script 100% Free Email Relay Active",
    titleHi: "गूगल ऐप्स स्क्रिप्ट 100% मुफ़्त ईमेल रिले सक्रिय",
    badge: "GAS Transactional",
    badgeColor: "emerald",
    highlight: true,
    descriptionEn: "Live diagnostic verification email received in client inbox (BlindShare Email Relay Active: Live Diagnostic Verified). Powered by Google Apps Script with 100 emails/day at ₹0 cost.",
    descriptionHi: "क्लाइंट इनबॉक्स में प्राप्त लाइव डायग्नोस्टिक सत्यापन ईमेल। Google Apps Script द्वारा ₹0 लागत पर 100 ईमेल/दिन की क्षमता के साथ संचालित।",
    tags: ["Google Apps Script", "₹0 Cost Email", "Diagnostic Verified", "DKIM/SPF"],
    proofPoints: [
      "100 free transactional emails per day via Gmail infrastructure",
      "Sub-2s delivery with zero SendGrid/Resend monthly bills",
      "Fully verified DKIM, SPF, and DMARC delivery compliance",
    ],
  },
  {
    id: "gas-admin-invite-email",
    filename: "brave_9lp57u15IS.png",
    category: "email",
    titleEn: "Admin Invitation Transactional Email Delivery",
    titleHi: "एडमिन आमंत्रण ट्रांजेक्शनल ईमेल डिलीवरी",
    badge: "Invite Delivery",
    badgeColor: "blue",
    descriptionEn: "Transactional admin invite email delivering a cryptographically signed registration token (sherinv_...) with one-click genesis onboarding and expiration control.",
    descriptionHi: "ट्रांजेक्शनल एडमिन आमंत्रण ईमेल जो क्रिप्टोग्राफिक रूप से हस्ताक्षरित पंजीकरण टोकन (sherinv_...) वन-क्लिक जेनेसिस ऑनबोर्डिंग के साथ प्रदान करता है।",
    tags: ["Invite Tokens", "Zero-Phish Architecture", "Role-Based Access"],
    proofPoints: [
      "Cryptographically signed invite token with expiration",
      "Formatted magic button and fallback registration code",
      "Zero plaintext password or secret leaks in email body",
    ],
  },

  // ==========================================
  // 4. INFRASTRUCTURE, HEALTH & AUDIT LEDGER
  // ==========================================
  {
    id: "admin-system-diagnostics",
    filename: "brave_GvQULOUNpK.png",
    category: "admin",
    titleEn: "Admin System Diagnostics (Neon DB & B2 Latency)",
    titleHi: "एडमिन सिस्टम डायग्नोस्टिक्स (Neon DB और B2 लेटेंसी)",
    badge: "System Health",
    badgeColor: "emerald",
    highlight: true,
    descriptionEn: "Live admin diagnostics report verifying Neon PostgreSQL connection (224ms ping), Backblaze B2 S3 storage (28ms ping), active cryptographic engine, and 54 validated environment variables.",
    descriptionHi: "लाइव एडमिन डायग्नोस्टिक्स रिपोर्ट जो Neon PostgreSQL कनेक्शन (224ms), Backblaze B2 स्टोरेज (28ms), सक्रिय क्रिप्टोग्राफ़िक इंजन और 54 सत्यापित एनवायरनमेंट वेरिएबल्स की पुष्टि करती है।",
    tags: ["Neon PostgreSQL", "Backblaze B2", "Sub-30ms Latency", "54 Env Vars"],
    proofPoints: [
      "Live Neon DB latency check (224ms)",
      "Backblaze B2 sub-30ms ping (28ms)",
      "100% cryptographic subsystem readiness confirmed",
    ],
  },
  {
    id: "admin-storage-footprint",
    filename: "brave_TnjWnN8Uho.png",
    category: "admin",
    titleEn: "Zero-Mock Real Storage Footprint Inspector",
    titleHi: "शून्य-मॉक वास्तविक स्टोरेज फुटप्रिंट इंस्पेक्टर",
    badge: "Real Storage",
    badgeColor: "amber",
    descriptionEn: "Live storage footprint inspector displaying genuine database utilization (9.34 MB / 512 MB on Neon DB) and B2 vault metrics (2.46 MB / 10 GB). Zero artificial mock math.",
    descriptionHi: "लाइव स्टोरेज फुटप्रिंट इंस्पेक्टर जो वास्तविक डेटाबेस उपयोग (Neon DB पर 9.34 MB / 512 MB) और B2 वॉल्ट मेट्रिक्स (2.46 MB / 10 GB) प्रदर्शित करता है। शून्य नकली डेटा।",
    tags: ["Real Storage Stats", "Zero Mock Data", "Neon DB", "Backblaze B2"],
    proofPoints: [
      "Real query: SELECT pg_database_size() from Neon PostgreSQL",
      "Real Backblaze B2 API bucket byte summation",
      "Strict compliance with Zero Fake/Mock Data directive",
    ],
  },
  {
    id: "admin-storage-maintenance",
    filename: "brave_xc8cQo3S74.png",
    category: "admin",
    titleEn: "Storage Maintenance & Orphan Object Sweeper",
    titleHi: "स्टोरेज मेंटेनेंस और अनाथ ऑब्जेक्ट स्वीपर",
    badge: "Garbage Collection",
    badgeColor: "rose",
    descriptionEn: "Automated storage maintenance engine performing orphan object sweeps on B2/R2, purging soft-deleted tombstones, and cleaning expired share links to prevent storage bloat.",
    descriptionHi: "स्वचालित स्टोरेज मेंटेनेंस इंजन जो B2/R2 पर अनाथ ऑब्जेक्ट स्वीप करता है, सॉफ्ट-डिलीटेड टॉम्बस्टोन को हटाता है, और स्टोरेज ब्लोट को रोकने के लिए समाप्त हो चुके शेयर लिंक को साफ़ करता है।",
    tags: ["Orphan Sweeper", "Tombstone Purge", "DB Vacuum", "Storage Pruning"],
    proofPoints: [
      "Sweeps dangling B2 ciphertext chunks with no DB reference",
      "Prunes expired share links and associated access logs",
      "Maintains zero-waste 512 MB Neon and 10 GB B2 free tier quotas",
    ],
  },
  {
    id: "admin-blind-audit-ledger",
    filename: "brave_cY6swqN4a1.png",
    category: "admin",
    titleEn: "Immutable Blind Security Audit Ledger",
    titleHi: "अपरिवर्तनीय ब्लाइंड सुरक्षा ऑडिट लेजर",
    badge: "Audit Trail",
    badgeColor: "blue",
    descriptionEn: "Cryptographically sequenced audit trail recording sensitive security events (link.create, doc.upload, doc.crypto_shred, auth.2fa_enabled) with SHA-256 chain integrity.",
    descriptionHi: "क्रिप्टोग्राफिक रूप से अनुक्रमित ऑडिट ट्रेल जो संवेदनशील सुरक्षा घटनाओं (link.create, doc.upload, doc.crypto_shred) को SHA-256 श्रृंखला अखंडता के साथ रिकॉर्ड करता है।",
    tags: ["Audit Ledger", "SHA-256 Hash Chain", "CEF-Compliant", "SIEM Ready"],
    proofPoints: [
      "Tamper-evident hash-chained security event log",
      "Zero plaintext sensitive metadata recorded",
      "Exportable for enterprise SOC2 and ISO 27001 compliance",
    ],
  },
  {
    id: "admin-invite-generator",
    filename: "brave_T7bLtlKEc8.png",
    category: "admin",
    titleEn: "Role-Based Registration Invite Generator",
    titleHi: "भूमिका-आधारित पंजीकरण आमंत्रण जनरेटर",
    badge: "Genesis Access",
    badgeColor: "purple",
    descriptionEn: "Admin interface for provisioning role-based, time-expiring invitation codes (admin, owner). Restricts public signups while enabling authorized team expansion.",
    descriptionHi: "भूमिका-आधारित, समय-समाप्त आमंत्रण कोड (admin, owner) जारी करने के लिए एडमिन इंटरफ़ेस। अधिकृत टीम विस्तार को सक्षम करते हुए सार्वजनिक साइनअप को प्रतिबंधित करता है।",
    tags: ["Invite Tokens", "RBAC", "Genesis Control", "Access Security"],
    proofPoints: [
      "Strict control over platform user growth",
      "Configurable 24h/7d expiration time-locks",
      "Cryptographic token hashing before database storage",
    ],
  },

  // ==========================================
  // 5. CLIENT-SIDE ENCRYPTION, GATES & ONBOARDING
  // ==========================================
  {
    id: "super-admin-genesis",
    filename: "brave_zKb6k3akcq.png",
    category: "gates",
    titleEn: "Genesis Super Admin Registration with ALTCHA",
    titleHi: "ALTCHA के साथ जेनेसिस सुपर एडमिन पंजीकरण",
    badge: "Genesis Setup",
    badgeColor: "amber",
    descriptionEn: "One-time Genesis Super Admin setup screen featuring self-hosted ALTCHA Proof-of-Work anti-bot protection and zero-telemetry local password strength calculation.",
    descriptionHi: "वन-टाइम जेनेसिस सुपर एडमिन सेटअप स्क्रीन जिसमें सेल्फ-होस्टेड ALTCHA प्रूफ-ऑफ-वर्क एंटी-बॉट सुरक्षा और शून्य-टेलीमेट्री स्थानीय पासवर्ड शक्ति गणना शामिल है।",
    tags: ["ALTCHA PoW", "Genesis Admin", "Anti-Bot", "Self-Hosted"],
    proofPoints: [
      "Self-hosted cryptographic SHA-256 proof-of-work challenge",
      "Zero Google reCAPTCHA tracking cookies or third-party scripts",
      "One-time initialization lock prevents secondary genesis attacks",
    ],
  },
  {
    id: "admin-onboarding-strength",
    filename: "brave_eJinVE5Tai.png",
    category: "gates",
    titleEn: "Enterprise Password Strength & Entropy Validator",
    titleHi: "एंटरप्राइज़ पासवर्ड शक्ति और एन्ट्रॉपी सत्यापनकर्ता",
    badge: "Entropy Check",
    badgeColor: "emerald",
    descriptionEn: "Interactive password entropy validator with real-time feedback ensuring high-entropy passphrases before master vault derivation and Argon2id hashing.",
    descriptionHi: "रीयल-टाइम फीडबैक के साथ इंटरैक्टिव पासवर्ड एन्ट्रॉपी सत्यापनकर्ता जो मास्टर वॉल्ट व्युत्पत्ति से पहले उच्च-एन्ट्रॉपी पासफ़्रेज़ सुनिश्चित करता है।",
    tags: ["Password Entropy", "Client-Side Validation", "Security Hardening"],
    proofPoints: [
      "Zxcvbn-style entropy calculation in browser",
      "Enforces minimum 12-char length with mixed character sets",
      "Pre-validates against common compromised dictionary lists",
    ],
  },
  {
    id: "document-upload-flow",
    filename: "brave_qPrN3yk6BV.png",
    category: "gates",
    titleEn: "Client-Side Document Encryption & Upload Flow",
    titleHi: "क्लाइंट-साइड दस्तावेज़ एन्क्रिप्शन और अपलोड प्रवाह",
    badge: "In-Browser E2EE",
    badgeColor: "blue",
    descriptionEn: "Upload modal performing in-browser WebCrypto AES-GCM-256 encryption. The file is encrypted locally in RAM before transmitting encrypted ciphertext chunks to storage.",
    descriptionHi: "अपलोड मोडल जो इन-ब्राउज़र WebCrypto AES-GCM-256 एन्क्रिप्शन निष्पादित करता है। स्टोरेज में भेजने से पहले फ़ाइल को रैम में स्थानीय रूप से एन्क्रिप्ट किया जाता है।",
    tags: ["WebCrypto", "In-Browser Encryption", "AES-GCM-256", "Zero Server Knowledge"],
    proofPoints: [
      "100% RAM-isolated encryption before any network packet is dispatched",
      "Generates random 256-bit AES key per document",
      "Browser memory wiped post-upload with zeroizeBuffer()",
    ],
  },
  {
    id: "generated-zk-link-fragment",
    filename: "brave_ksQFF8RRXR.png",
    category: "gates",
    titleEn: "Generated Zero-Knowledge URL (#k=...) Link Fragment",
    titleHi: "जनरेट किया गया शून्य-ज्ञान URL (#k=...) लिंक फ्रैगमेंट",
    badge: "RFC 3986 Invariant",
    badgeColor: "emerald",
    highlight: true,
    descriptionEn: "Generated secure document sharing link displaying the cryptographic fragment #k=.... In accordance with RFC 3986, browsers never transmit this fragment to HTTP servers or logs.",
    descriptionHi: "उत्पन्न सुरक्षित दस्तावेज़ शेयर लिंक जो क्रिप्टोग्राफ़िक फ्रैगमेंट #k=... प्रदर्शित करता है। RFC 3986 के अनुसार ब्राउज़र इसे कभी भी सर्वर या लॉग में नहीं भेजते।",
    tags: ["URL Fragment", "RFC 3986", "Key Courier", "Zero Log Leakage"],
    proofPoints: [
      "URL fragment is strictly client-side per RFC 3986",
      "Server access logs and reverse proxies capture 0 bytes of key",
      "One-click copy with ephemeral QR code generation",
    ],
  },
  {
    id: "link-studio-modal-1",
    filename: "brave_SrkW9m1rpy.png",
    category: "gates",
    titleEn: "Link Studio: Security Controls & Dynamic Watermarking",
    titleHi: "लिंक स्टूडियो: सुरक्षा नियंत्रण और गतिशील वॉटरमार्किंग",
    badge: "Link Studio",
    badgeColor: "purple",
    descriptionEn: "Link Studio configuration panel displaying granular security controls: Passphrase protection, Email gate capture, Dynamic diagonal watermarking, and Expiration timers.",
    descriptionHi: "लिंक स्टूडियो कॉन्फ़िगरेशन पैनल जिसमें विस्तृत सुरक्षा नियंत्रण हैं: पासफ़्रेज़ सुरक्षा, ईमेल गेट कैप्चर, डायनेमिक विकर्ण वॉटरमार्किंग और समाप्ति टाइमर।",
    tags: ["Passcode Gate", "Email Capture", "Dynamic Watermark", "Expiration"],
    proofPoints: [
      "Dynamic viewer email watermark projection on document canvas",
      "Mandatory email gate to identify readers before decryption",
      "Granular expiration time-locks with sub-minute precision",
    ],
  },
  {
    id: "link-studio-modal-2",
    filename: "brave_ulWNGF5nWO.png",
    category: "gates",
    titleEn: "Link Studio: NDA Clickwrap & Anti-Spy Defenses",
    titleHi: "लिंक स्टूडियो: एनडीए क्लिकरैप और एंटी-जासूसी सुरक्षा",
    badge: "Anti-Exfiltration",
    badgeColor: "rose",
    highlight: true,
    descriptionEn: "Advanced security toggles in Link Studio: Mandatory NDA Clickwrap agreement, Burn-After-Reading ratchet, Anti-Capture window blur, and Tab-Switch Anti-Spy defense shield.",
    descriptionHi: "लिंक स्टूडियो में उन्नत सुरक्षा विकल्प: अनिवार्य एनडीए क्लिकरैप समझौता, पढ़ने के बाद नष्ट (Burn), एंटी-कैप्चर विंडो ब्लर, और टैब-स्विच एंटी-स्पाई शील्ड।",
    tags: ["NDA Clickwrap", "Burn After Reading", "Anti-Spy Shield", "Capture Blur"],
    proofPoints: [
      "Tab-switch shield pauses reading and obfuscates canvas when tab loses focus",
      "Burn ratchet invalidates decryption keys after configured view count",
      "Clickwrap NDA timestamped and logged with viewer IP hash",
    ],
  },
  {
    id: "viewer-access-gate-modal",
    filename: "brave_XyJO2IR0zL.png",
    category: "gates",
    titleEn: "Protected Viewer Access Gate (Email + NDA + ALTCHA)",
    titleHi: "सुरक्षित व्यूअर एक्सेस गेट (ईमेल + एनडीए + ALTCHA)",
    badge: "Access Gate",
    badgeColor: "amber",
    descriptionEn: "Live reader gate presented before document decryption. Enforces verified email entry, legally binding NDA clickwrap acceptance, and automated ALTCHA Proof-of-Work bot check.",
    descriptionHi: "दस्तावेज़ डिक्रिप्शन से पहले प्रस्तुत किया गया लाइव रीडर गेट। सत्यापित ईमेल प्रविष्टि, कानूनी रूप से बाध्यकारी एनडीए स्वीकृति और स्वचालित ALTCHA बॉट चेक लागू करता है।",
    tags: ["Email Verification", "NDA Agreement", "ALTCHA PoW", "Gate Enforcement"],
    proofPoints: [
      "Decryption blocked until server gate token is validated",
      "Legally binding confidentiality clause acceptance",
      "Protects pitch decks from automated web crawlers and scraping bots",
    ],
  },
  {
    id: "two-factor-qr-setup",
    filename: "brave_5Oh8XVWJiD.png",
    category: "gates",
    titleEn: "Two-Factor Authentication (TOTP QR Provisioning)",
    titleHi: "टू-फैक्टर प्रमाणीकरण (TOTP QR सेटअप)",
    badge: "2FA TOTP",
    badgeColor: "emerald",
    descriptionEn: "Two-Factor Authentication setup modal displaying an RFC 6238 TOTP QR code for Google Authenticator / 1Password, along with a base32 manual backup secret.",
    descriptionHi: "टू-फैक्टर प्रमाणीकरण सेटअप मोडल जो Google Authenticator / 1Password के लिए RFC 6238 TOTP QR कोड और बेस32 मैनुअल बैकअप कुंजी प्रदर्शित करता है।",
    tags: ["2FA", "TOTP", "RFC 6238", "Authenticator App"],
    proofPoints: [
      "Hardware token & authenticator app compatibility",
      "Client-side QR generation with zero external analytics tracking",
      "Secret encrypted with owner master key before database persistence",
    ],
  },
  {
    id: "two-factor-challenge-screen",
    filename: "brave_ZzZcU246iw.png",
    category: "gates",
    titleEn: "2FA Verification Challenge & Emergency Backup Codes",
    titleHi: "2FA सत्यापन चुनौती और आपातकालीन बैकअप कोड",
    badge: "2FA Active",
    badgeColor: "blue",
    descriptionEn: "TOTP 6-digit challenge prompt confirming 2FA activation, complete with cryptographic single-use backup recovery codes for secure emergency account recovery.",
    descriptionHi: "TOTP 6-अंकीय सत्यापन प्रॉम्ट जो 2FA सक्रियण की पुष्टि करता है, आपातकालीन खाता पुनर्प्राप्ति के लिए एकल-उपयोग बैकअप रिकवरी कोड के साथ।",
    tags: ["Backup Codes", "Recovery Secrets", "Security Verification"],
    proofPoints: [
      "Bcrypt-hashed single-use emergency backup recovery codes",
      "Rate-limited TOTP verification window (prevents brute-force)",
      "Protects administrative account against session hijacking",
    ],
  },

  // ==========================================
  // 6. SECURE DOCUMENT VIEWER & INTERACTIVE Q&A
  // ==========================================
  {
    id: "secure-viewer-watermark",
    filename: "brave_WGPvXSEEGx.png",
    category: "viewer",
    titleEn: "Secure 288-Page Hindi PDF Viewer with Dynamic Watermark",
    titleHi: "गतिशील वॉटरमार्क के साथ सुरक्षित 288-पृष्ठ हिंदी पीडीएफ व्यूअर",
    badge: "Secure Canvas",
    badgeColor: "emerald",
    highlight: true,
    descriptionEn: "High-performance browser PDF viewer rendering a 288-page Hindi document with dynamic diagonal watermark (demo@gmail.com), navigation bar, thumbnails, and cyber pet companion.",
    descriptionHi: "उच्च प्रदर्शन वाला ब्राउज़र पीडीएफ व्यूअर जो 288-पृष्ठ के हिंदी दस्तावेज़ को डायनामिक विकर्ण वॉटरमार्क (demo@gmail.com), नेविगेशन बार और थंबनेल के साथ प्रस्तुत करता है।",
    tags: ["Dynamic Watermark", "288-Page PDF", "Hindi Support", "Cyber Pet Companion"],
    proofPoints: [
      "Non-removable HTML5 canvas dynamic watermark layer",
      "Header-to-footer unrestricted smooth scrolling",
      "Client-side per-slide HKDF key derivation for instant rendering",
    ],
  },
  {
    id: "secure-viewer-ergonomics",
    filename: "brave_ZAzBNcK66w.png",
    category: "viewer",
    titleEn: "Dual Fit Engine & Header-to-Footer Ergonomics",
    titleHi: "डुअल फिट इंजन और हेडर-टू-फुटर एर्गोनॉमिक्स",
    badge: "Viewer Ergonomics",
    badgeColor: "blue",
    descriptionEn: "Document viewer showcasing dual fit mode (Fit Width vs Fit Page), isolated mouse wheel navigation, thumbnail preview rail, and zoom magnification controls.",
    descriptionHi: "दस्तावेज़ व्यूअर जो डुअल फिट मोड (Fit Width बनाम Fit Page), अलग माउस व्हील नेविगेशन, थंबनेल पूर्वावलोकन रेल और ज़ूम नियंत्रण प्रदर्शित करता है।",
    tags: ["Dual Fit Engine", "Fit Width", "Fit Page", "Smooth Zoom"],
    proofPoints: [
      "Pixel-perfect responsive scaling across 4K monitors and mobile phones",
      "Isolated wheel events prevent parent page scroll hijacking",
      "Page dwell telemetry paused automatically when tab is hidden",
    ],
  },
  {
    id: "slide-qa-pin-selection",
    filename: "brave_kiqWuRIf2T.png",
    category: "viewer",
    titleEn: "Interactive Slide Q&A: Coordinate Pin Placement",
    titleHi: "इंटरैक्टिव स्लाइड प्रश्नोत्तरी: निर्देशांक पिन स्थापन",
    badge: "Slide Q&A",
    badgeColor: "amber",
    descriptionEn: "Reader placing an interactive question pin directly onto Slide 1 canvas. Enables contextual questions pinned to specific charts, financial figures, or bullet points.",
    descriptionHi: "पाठक द्वारा सीधे स्लाइड 1 कैनवास पर एक इंटरैक्टिव प्रश्न पिन रखना। विशिष्ट चार्ट, वित्तीय आंकड़ों या बिंदुओं पर प्रासंगिक प्रश्न पूछने में सक्षम बनाता है।",
    tags: ["Slide Pinning", "Interactive Q&A", "Canvas Coordinates", "Reader Engagement"],
    proofPoints: [
      "Precision relative X/Y coordinate storage on slide canvas",
      "Reader privacy isolation (readers only see their own questions)",
      "Instant telemetry trigger alerting founder on Stoat and email",
    ],
  },
  {
    id: "slide-qa-question-compose",
    filename: "brave_NXg4xHhYaN.png",
    category: "viewer",
    titleEn: "Interactive Slide Q&A: Question Submission Modal",
    titleHi: "इंटरैक्टिव स्लाइड प्रश्नोत्तरी: प्रश्न सबमिशन मोडल",
    badge: "Question Compose",
    badgeColor: "purple",
    descriptionEn: "Slide Q&A question modal allowing readers to compose confidential inquiries about specific presentation details without leaving the secure viewing experience.",
    descriptionHi: "स्लाइड प्रश्नोत्तरी मोडल जो पाठकों को सुरक्षित देखने के अनुभव को छोड़े बिना विशिष्ट प्रस्तुति विवरणों के बारे में गोपनीय पूछताछ करने की अनुमति देता है।",
    tags: ["In-Doc Q&A", "Confidential Inquiries", "Reader Privacy"],
    proofPoints: [
      "Client-side input sanitization against XSS payloads",
      "Direct association with active document share link",
      "Zero public leakage to competing investors reading same link",
    ],
  },
  {
    id: "slide-qa-rendered-pin",
    filename: "brave_H4Br4owHrn.png",
    category: "viewer",
    titleEn: "Interactive Slide Q&A: Real-Time Pin on Canvas",
    titleHi: "इंटरैक्टिव स्लाइड प्रश्नोत्तरी: कैनवास पर रीयल-टाइम पिन",
    badge: "Live Pin",
    badgeColor: "rose",
    descriptionEn: "Visual rendering of active question pin on slide canvas with pulsating indicator, status badge, and hover preview of question thread.",
    descriptionHi: "स्पंदनशील संकेतक, स्थिति बैज और प्रश्न थ्रेड के होवर पूर्वावलोकन के साथ स्लाइड कैनवास पर सक्रिय प्रश्न पिन का दृश्य रेंडरिंग।",
    tags: ["Pulsing Pin", "Canvas Overlay", "Thread Status"],
    proofPoints: [
      "Real-time visual coordinate placement on top of decrypted PDF canvas",
      "Read/unread status tracking for founder replies",
      "High-contrast visibility across light and dark PDF slide backgrounds",
    ],
  },
  {
    id: "slide-qa-founder-inbox",
    filename: "brave_HopjAoBcun.png",
    category: "viewer",
    titleEn: "Founder Q&A Management & Thread Reply Inbox",
    titleHi: "संस्थापक प्रश्नोत्तरी प्रबंधन और थ्रेड उत्तर इनबॉक्स",
    badge: "Q&A Inbox",
    badgeColor: "emerald",
    descriptionEn: "Founder dashboard Q&A Inbox showing questions organized by document and slide, allowing the founder to review queries and send confidential answers back to the reader.",
    descriptionHi: "संस्थापक डैशबोर्ड प्रश्नोत्तरी इनबॉक्स जो दस्तावेज़ और स्लाइड द्वारा व्यवस्थित प्रश्न दिखाता है, जिससे संस्थापक प्रश्नों की समीक्षा कर पाठक को उत्तर भेज सकता है।",
    tags: ["Founder Inbox", "Thread Replies", "Deal Acceleration"],
    proofPoints: [
      "Full conversation history linked to specific slide numbers",
      "Confidential responses delivered directly to reader's in-doc session",
      "Accelerates diligence process during active fundraising rounds",
    ],
  },
  {
    id: "document-fullscreen-inspection",
    filename: "brave_3iRp1Yic0W.png",
    category: "viewer",
    titleEn: "Full-Canvas Immersive Presentation Inspection",
    titleHi: "पूर्ण-कैनवास इमर्सिव प्रेजेंटेशन निरीक्षण",
    badge: "Fullscreen Mode",
    badgeColor: "blue",
    descriptionEn: "Immersive fullscreen document reading experience with distraction-free controls, slide carousel navigator, and live telemetry tracking active reading speed.",
    descriptionHi: "व्याकुलता-मुक्त नियंत्रण, स्लाइड हिंडोला नेविगेटर और पढ़ने की गति को ट्रैक करने वाले लाइव टेलीमेट्री के साथ इमर्सिव फुलस्क्रीन दस्तावेज़ पाठन अनुभव।",
    tags: ["Fullscreen Canvas", "Immersive Reading", "Telemetry Tracking"],
    proofPoints: [
      "Zero distraction interface for executive deck review",
      "Keyboard shortcuts for rapid slide navigation (Arrow keys, Space)",
      "High-DPI vector PDF rendering powered by WebAssembly PDF engine",
    ],
  },

  // ==========================================
  // 7. DEEP ANALYTICS & DUCKDB TELEMETRY
  // ==========================================
  {
    id: "analytics-truthful-zero-state",
    filename: "brave_qlXpwmfF1X.png",
    category: "analytics",
    titleEn: "Strict Zero Fake Data Policy: Truthful Zero State",
    titleHi: "सख्त शून्य नकली डेटा नीति: सच्चा शून्य स्थिति डैशबोर्ड",
    badge: "Zero Fake Data",
    badgeColor: "emerald",
    highlight: true,
    descriptionEn: "Clean, honest zero-state dashboard before traffic arrives. Displays 0 views, 0 sessions, and empty state guides. Proves complete elimination of fake dummy graphs and synthetic VC records.",
    descriptionHi: "ट्रैफ़िक आने से पहले स्वच्छ, ईमानदार शून्य-स्थिति डैशबोर्ड। 0 दृश्य, 0 सत्र प्रदर्शित करता है। नकली डमी ग्राफ़ और सिंथेटिक रिकॉर्ड के पूर्ण उन्मूलन को सिद्ध करता है।",
    tags: ["Strict Zero Fake Data", "Truthful Empty State", "Drizzle ORM", "No Mocking"],
    proofPoints: [
      "Zero random math generators or artificial curves",
      "Clean onboarding empty-state cards guiding initial upload",
      "100% computed from real Neon PostgreSQL database queries",
    ],
  },
  {
    id: "analytics-populated-dashboard",
    filename: "brave_kdj9xJeKxV.png",
    category: "analytics",
    titleEn: "Live Analytics Dashboard with Verified Telemetry",
    titleHi: "सत्यापित टेलीमेट्री के साथ लाइव एनालिटिक्स डैशबोर्ड",
    badge: "Live Telemetry",
    badgeColor: "amber",
    highlight: true,
    descriptionEn: "Production analytics dashboard populated with authentic reader engagement data: Active links, total view sessions, average dwell duration, and geographic footprint.",
    descriptionHi: "प्रामाणिक पाठक सहभागिता डेटा के साथ लाइव एनालिटिक्स डैशबोर्ड: सक्रिय लिंक, कुल दृश्य सत्र, औसत पढ़ने का समय और भौगोलिक पदचिह्न।",
    tags: ["Live Dashboard", "Dwell Time", "Reader Sessions", "Real Metrics"],
    proofPoints: [
      "Aggregates authentic reader telemetry across all shared documents",
      "Dynamic KPI trend indicators based on genuine historical delta",
      "Instant response powered by in-memory DuckDB analytical engine",
    ],
  },
  {
    id: "analytics-realtime-overview",
    filename: "brave_Cf1uBsiaG6.png",
    category: "analytics",
    titleEn: "Real-Time Engagement Overview (Live Readers & Dwell)",
    titleHi: "रीयल-टाइम सहभागिता अवलोकन (लाइव पाठक और ड्वेल समय)",
    badge: "Real-Time Telemetry",
    badgeColor: "blue",
    descriptionEn: "Live engagement summary showing active readers right now (1 Live), total reading time (2m 30s), desktop vs mobile distribution, and Indian geolocation origin.",
    descriptionHi: "लाइव सहभागिता सारांश जो इस समय सक्रिय पाठकों (1 लाइव), कुल पाठन समय (2 मिनट 30 सेकंड), डेस्कटॉप बनाम मोबाइल और भारतीय भौगोलिक मूल को दर्शाता है।",
    tags: ["Real-Time Readers", "Live Dwell", "Device Split", "Geolocation"],
    proofPoints: [
      "Heartbeat telemetry detects active reader presence in sub-5s",
      "Automated dwell calculation accurately measures reading attention",
      "Browser & OS fingerprinting without violating user privacy",
    ],
  },
  {
    id: "analytics-engagement-heatmap-stream",
    filename: "brave_sfeDwvXr9a.png",
    category: "analytics",
    titleEn: "365-Day Activity Heatmap & High-Intent Live Stream",
    titleHi: "365-दिवसीय गतिविधि हीटमैप और उच्च-इरादा लाइव स्ट्रीम",
    badge: "Heatmap & Stream",
    badgeColor: "emerald",
    highlight: true,
    descriptionEn: "GitHub-style 365-day engagement calendar matrix paired with an instant Live Activity Stream. Automatically flags high-conviction viewers with intent scoring (High Intent).",
    descriptionHi: "GitHub-शैली 365-दिवसीय सहभागिता कैलेंडर मैट्रिक्स और त्वरित लाइव गतिविधि स्ट्रीम। इरादा स्कोरिंग (उच्च इरादा) के साथ निवेशकों को स्वचालित रूप से चिह्नित करता है।",
    tags: ["365-Day Heatmap", "Activity Stream", "Intent Scoring", "Deal Signals"],
    proofPoints: [
      "Continuous chronological ledger of all link and document views",
      "Automated high-intent scoring algorithm based on dwell velocity",
      "Click-through session replay for detailed reading breakdowns",
    ],
  },
  {
    id: "analytics-retention-funnel-hub",
    filename: "brave_668uP09lqE.png",
    category: "analytics",
    titleEn: "Per-Link Analytics Hub & 5-Stage Retention Funnel",
    titleHi: "प्रति-लिंक एनालिटिक्स हब और 5-चरणीय प्रतिधारण फ़नल",
    badge: "Retention Funnel",
    badgeColor: "purple",
    descriptionEn: "Granular per-link analytics interface showing 5-stage reader retention funnel (Link Clicked -> Gate Passed -> Page 1 Viewed -> Midpoint -> Final Slide) with drop-off cliff alerts.",
    descriptionHi: "विस्तृत प्रति-लिंक एनालिटिक्स इंटरफ़ेस जो 5-चरणीय पाठक प्रतिधारण फ़नल और गिरावट अलर्ट प्रदर्शित करता है।",
    tags: ["Retention Funnel", "Drop-Off Alerts", "Per-Link Analytics", "Funnel Stages"],
    proofPoints: [
      "Pinpoints exact slide where prospective investors lose interest",
      "Identifies conversion cliffs to optimize pitch deck storytelling",
      "100% computed from atomic page view event timestamps",
    ],
  },
  {
    id: "analytics-page-dwell-spline",
    filename: "brave_NahVot5a9R.png",
    category: "analytics",
    titleEn: "Cubic Spline Page Dwell & Attention Velocity Chart",
    titleHi: "क्यूबिक स्प्लाइन पेज ड्वेल और ध्यान वेग चार्ट",
    badge: "Attention Velocity",
    badgeColor: "rose",
    highlight: true,
    descriptionEn: "Interactive cubic spline curve displaying reader attention across all pages. Highlights peak engagement spikes on financial models, architecture slides, and team bios.",
    descriptionHi: "सभी पृष्ठों पर पाठक के ध्यान को प्रदर्शित करने वाला इंटरैक्टिव क्यूबिक स्प्लाइन वक्र। वित्तीय मॉडल और आर्किटेक्चर स्लाइड पर जुड़ाव को उजागर करता है।",
    tags: ["Cubic Spline", "Dwell Curves", "Attention Spikes", "SVG Vector Suite"],
    proofPoints: [
      "Dynamic SVG vector chart with smooth 3D perspective tilt",
      "Hover tooltips showing exact seconds spent per slide",
      "Calculates drop-off acceleration between consecutive pages",
    ],
  },
  {
    id: "analytics-slide-heatmap-table",
    filename: "brave_hWmy8aftd3.png",
    category: "analytics",
    titleEn: "Page-by-Page Dwell Heatmap (Slide 2: 5m 3s Peak)",
    titleHi: "पृष्ठ-दर-पृष्ठ ड्वेल हीटमैप (स्लाइड 2: 5 मिनट 3 सेकंड पीक)",
    badge: "Slide Heatmap",
    badgeColor: "amber",
    descriptionEn: "Tabular slide-by-slide dwell time heatmap revealing that readers spent 5 minutes and 3 seconds examining Slide 2, identifying intense investor diligence on core unit economics.",
    descriptionHi: "तालिकाबद्ध स्लाइड-दर-स्लाइड ड्वेल टाइम हीटमैप जिससे पता चलता है कि पाठकों ने स्लाइड 2 की जांच करने में 5 मिनट 3 सेकंड बिताए।",
    tags: ["Dwell Heatmap", "Slide Diligence", "Peak Reading Time", "Unit Economics"],
    proofPoints: [
      "Color-coded dwell intensity bars based on percent of total time",
      "Tracks re-reads (readers navigating backward to revisit slides)",
      "Highlights key diligence focal points for founder follow-up",
    ],
  },
  {
    id: "analytics-device-deal-temperature",
    filename: "brave_7WlelRyZj9.png",
    category: "analytics",
    titleEn: "Device Distribution & Deal Temperature Meter",
    titleHi: "डिवाइस वितरण और डील टेम्परेचर मीटर",
    badge: "Deal Temperature",
    badgeColor: "blue",
    descriptionEn: "Visual breakdown of reader hardware (100% Desktop) combined with an automated algorithmic Deal Temperature Meter rating buyer excitement from Warm to Scorching.",
    descriptionHi: "पाठक हार्डवेयर (100% डेस्कटॉप) का दृश्य विवरण और क्रेता के उत्साह को मापने वाला स्वचालित डील टेम्परेचर मीटर।",
    tags: ["Device Analytics", "Deal Temperature", "Investor Signals", "Deal Closing"],
    proofPoints: [
      "Multi-factor scoring: dwell time + re-reads + questions asked + link shares",
      "Device category detection (Mobile vs Tablet vs Desktop)",
      "Guides founders on when to initiate term sheet discussions",
    ],
  },
  {
    id: "analytics-session-breakdown",
    filename: "brave_lZYdWpxz0d.png",
    category: "analytics",
    titleEn: "Individual Viewer Session Replay & Conviction Score",
    titleHi: "व्यक्तिगत व्यूअर सत्र विवरण और दृढ़ विश्वास स्कोर",
    badge: "Session Replay",
    badgeColor: "purple",
    descriptionEn: "Granular audit log of a single viewer's complete session. Shows exact enter/exit timestamps, pages navigated, total active reading seconds, and calculated conviction score.",
    descriptionHi: "एक ही दर्शक के पूर्ण सत्र का विस्तृत ऑडिट लॉग। सटीक प्रवेश/निकास समय, नेविगेट किए गए पृष्ठ, कुल सक्रिय सेकंड और स्कोर दिखाता है।",
    tags: ["Viewer Audit", "Session Replay", "Conviction Score", "Timeline"],
    proofPoints: [
      "Atomic timeline of every slide transition event",
      "Calculated completion rate (% of pitch deck completed)",
      "Completely isolated per individual share link token",
    ],
  },
  {
    id: "analytics-live-presence-indicator",
    filename: "brave_bdnDpfif08.png",
    category: "analytics",
    titleEn: "Real-Time Live Presence Telemetry Indicator",
    titleHi: "रीयल-टाइम लाइव उपस्थिति टेलीमेट्री संकेतक",
    badge: "Live Presence",
    badgeColor: "emerald",
    descriptionEn: "Live presence indicator showing real-time reader heartbeat. Flashes emerald pulsing status when a prospective investor is actively reading the pitch deck right now.",
    descriptionHi: "लाइव उपस्थिति संकेतक जो रीयल-टाइम पाठक दिल की धड़कन दिखाता है। जब कोई संभावित निवेशक अभी पढ़ रहा हो तो पल्सिंग पन्ना स्थिति चमकती है।",
    tags: ["Presence Telemetry", "Heartbeat Polling", "Live Signal"],
    proofPoints: [
      "Edge heartbeat websocket/polling mechanism",
      "Page Visibility API integration (pauses when viewer changes tab)",
      "Zero false-positive active reader reporting",
    ],
  },
  {
    id: "analytics-link-performance-leaderboard",
    filename: "brave_noOaOVOMtz.png",
    category: "analytics",
    titleEn: "Link Performance Comparison & Engagement Velocity",
    titleHi: "लिंक प्रदर्शन तुलना और सहभागिता वेग लीडरबोर्ड",
    badge: "Link Comparison",
    badgeColor: "blue",
    descriptionEn: "Comparative performance table ranking multiple active share links by view count, total reading time, average completion percentage, and recipient engagement velocity.",
    descriptionHi: "दृश्य संख्या, कुल पाठन समय, औसत पूर्णता प्रतिशत और सहभागिता वेग द्वारा कई सक्रिय शेयर लिंक की रैंकिंग करने वाली तुलनात्मक तालिका।",
    tags: ["Link Leaderboard", "Engagement Velocity", "A/B Link Testing"],
    proofPoints: [
      "Identifies which venture capital firm is most actively engaging",
      "Compare conversion rates across different distribution channels",
      "Sortable by total views, completion rate, or recent activity",
    ],
  },
  {
    id: "analytics-geolocation-distribution",
    filename: "brave_sI5HQ5KbGu.png",
    category: "analytics",
    titleEn: "Reader Geolocation Distribution (Country & City)",
    titleHi: "पाठक भौगोलिक स्थान वितरण (देश और शहर)",
    badge: "Geo Analytics",
    badgeColor: "amber",
    descriptionEn: "Geographic telemetry map and breakdown table displaying reader locations resolved from IP address without storing unhashed IP addresses in compliance with GDPR.",
    descriptionHi: "भौगोलिक टेलीमेट्री मैप और ब्रेकडाउन तालिका जो GDPR के अनुपालन में बिना अनहैशेड आईपी पते को स्टोर किए पाठक स्थानों को प्रदर्शित करती है।",
    tags: ["Geolocation", "GDPR Compliance", "Country Distribution", "City Resolution"],
    proofPoints: [
      "Privacy-preserving GeoIP lookup via edge headers",
      "IP addresses are SHA-256 salted and hashed before logging",
      "Visual country flag mapping and percentage contribution",
    ],
  },
  {
    id: "analytics-reading-habits-matrix",
    filename: "brave_tFUOQmcsQ9.png",
    category: "analytics",
    titleEn: "Time-of-Day Reading Habits Hourly Heatmap",
    titleHi: "दिन-के-समय पाठन की आदतें प्रति घंटा हीटमैप",
    badge: "Hourly Matrix",
    badgeColor: "purple",
    descriptionEn: "24-hour by 7-day hourly matrix charting reader engagement patterns. Reveals whether investors read the pitch deck during business hours, late evenings, or over weekends.",
    descriptionHi: "24-घंटे गुणा 7-दिन का प्रति घंटा मैट्रिक्स जो पाठक सहभागिता पैटर्न को चार्ट करता है। यह दर्शाता है कि निवेशक व्यावसायिक समय में पढ़ते हैं या सप्ताहांत में।",
    tags: ["Hourly Heatmap", "Reading Habits", "Investor Schedule", "Optimal Send Time"],
    proofPoints: [
      "Highlights optimal time-of-day windows for sending pitch follow-ups",
      "Aggregated in-memory via DuckDB without slow relational JOINs",
      "Normalizes across multiple viewer time zones automatically",
    ],
  },
  {
    id: "document-management-overview",
    filename: "brave_O3NReRlLXk.png",
    category: "analytics",
    titleEn: "Document Studio: Vault Overview & Quick Link Generation",
    titleHi: "दस्तावेज़ स्टूडियो: वॉल्ट अवलोकन और त्वरित लिंक निर्माण",
    badge: "Doc Studio",
    badgeColor: "emerald",
    descriptionEn: "Document Studio listing all encrypted vaults, page counts, created timestamps, and quick action menus for instant link creation, access revocation, and cryptographic shredding.",
    descriptionHi: "दस्तावेज़ स्टूडियो जो सभी एन्क्रिप्टेड वॉल्ट, पृष्ठ संख्या, टाइमस्टैम्प और त्वरित लिंक निर्माण, एक्सेस निरस्तीकरण और क्रिप्टोग्राफिक श्रेडिंग के मेनू को सूचीबद्ध करता है।",
    tags: ["Document Studio", "Vault Management", "Crypto Shredding", "Quick Share"],
    proofPoints: [
      "One-click cryptographic shredding permanently deletes B2 blobs and DB rows",
      "Instant share link generator with pre-configured security defaults",
      "Real-time page count and file size display",
    ],
  },
  {
    id: "full-platform-end-to-end-inspection",
    filename: "brave_ztHXsz4Akb.png",
    category: "analytics",
    titleEn: "Complete End-to-End BlindShare v1.4.1 High-Res Capture",
    titleHi: "पूर्ण एंड-टू-एंड ब्लाइंडशेयर v1.4.1 हाई-रेज़ोल्यूशन कैप्चर",
    badge: "Full Platform",
    badgeColor: "amber",
    highlight: true,
    descriptionEn: "Comprehensive ultra-high-resolution full page capture demonstrating the entire BlindShare production ecosystem from top navigation, live metrics, heatmaps, to security audit logs.",
    descriptionHi: "व्यापक अल्ट्रा-हाई-रेज़ोल्यूशन पूर्ण पृष्ठ कैप्चर जो शीर्ष नेविगेशन, लाइव मेट्रिक्स, हीटमैप्स से लेकर सुरक्षा ऑडिट लॉग तक पूरे ब्लाइंडशेयर इकोसिस्टम को प्रदर्शित करता है।",
    tags: ["Full Platform", "High-Res Audit", "Production Ecosystem", "v1.4.1"],
    proofPoints: [
      "Complete visual verification of BlindShare v1.4.1 production deployment",
      "Demonstrates harmonious integration across all 15 core architectural pillars",
      "Unmodified authentic capture directly from user testing session",
    ],
  },
];
